### ISSUE TITLE
Use input ID or object or jQuery object in constructor

### ISSUE THREAD

**Issue by Tiendq** [bevacqua/rome#101]
Hi,

Can you use input's string ID, or DOM object, or jQuery object in the constructor instead of literal ID value (like in example), it causes troubles with JSHint :(

<input id="test" type="text" value="">

rome("test"), or rom(document.getElementById("test")), or rome($("#test").... instead of

rome(**test**); // I don't where this code style is from, actually.

Thanks,

**Comment by bevacqua** [comment]
Use `rome(document.querySelector('#id'))` or pass in any element at all.

**Comment by chandika** [comment]
the rome(test) coding style is really odd. Perhaps mention it in the doc somewhere?

Typically, you'd pass a jquery selector or atleast a string class name to a constructor. This also has the limitation of element ID's to be syntactically correct JS variable names. so something like 'tx-date-picker' will not work.

**Comment by bevacqua** [comment]
It's up to you to figure out what elements to pass to `rome`. Not a concern of `rome`'s.
