### ISSUE TITLE
Select the year and set up year range

### ISSUE THREAD

**Issue by fcaballero** [bevacqua/rome#103]
Hi,
Currently is the user wants to select a different year, he must navigate until the year by clicking the arrows, so if the user wants to select his birthday, he have to click a as many times as years he is.
I want the user to be able to select the year of the date he wants to pick, but there is no way to configure that, or is there? For the months could be good as well.
Also it would be nice, to be able to configure the year range, as [jQuery datepicker](http://api.jqueryui.com/datepicker/#option-yearRange) does 

Regards

**Comment by bevacqua** [comment]
A PR to select the year and month by clicking on their labels would we welcome
