### ISSUE TITLE
can firing of data event when next or back is called be disabled?

### ISSUE THREAD

**Issue by diffalot** [bevacqua/rome#105]
I'm watching the `data` event in an angular directive to update the date of an angular model.

The trouble I'm running into is that the `data` event gets called when my users click the `next` or `back` month button on the calendar.  

This would not be a problem, but there are instances where the users may page through the months of the calendar, but not actually select a day, and in these cases I don't want the date to be set in my model.

Is there any known way to disable firing off `data` when `next` or `back` are fired? Or some way to only fire `data` when a numerical date has been selected from the calendar?  Is there another hidden method I can listen for that is fired off by numerical dates rather than `data`?  Or, finally, does anyone know of workarounds for this edge case of Rome usage?

**Comment by bevacqua** [comment]
It's been requested a lot to allow free navigation (e.g the displayed month changes but the actual value stays the same) when clicking on prev/next. You're free to submit a PR for that, behind an option flag.
