### ISSUE TITLE
Global defaults override

### ISSUE THREAD

**Issue by pekala** [bevacqua/rome#108]
Is it possible to override default options on the `rome` object, e.g. when I create multiple datepickers I don't have to specify the same options every time?

**Comment by bevacqua** [comment]
Not really, you'd have to do that outside of rome

**Comment by LasagnaAndroid** [comment]
You could easily make a wrapper of rome passing the options and using that instead, ex:

    var romeWrapper = function(element) {
       
        rome(element, options = {
            // your options here
        });
    }

or make a pr with a default/global options.
