### ISSUE TITLE
Add option to hide next and last month days from calendar

### ISSUE THREAD

**Issue by jordangarside** [bevacqua/rome#128]
Part of the days for the previous and next months are showing up in the calendar. It would be nice to be able to disable this so that only the days from the current month are shown.

**Comment by bevacqua** [comment]
Use CSS for that

**Comment by jordangarside** [comment]
You're right, didn't think about setting opacity: 0.

If you set `display: none;` you'll get this:
![image](https://cloud.githubusercontent.com/assets/6321824/9450378/234d5d26-4a5d-11e5-81da-6c388bc070cc.png)

If you set `opacity: 0;` you'll get this:
![image](https://cloud.githubusercontent.com/assets/6321824/9450414/4f4f8412-4a5d-11e5-8226-9efdc33b9ddc.png)

**Comment by erwinw** [comment]
Be aware that with opacity:0 the links are still clickable; use visibility:hidden instead. (Not at a desktop so working from memory here....)

**Comment by jordangarside** [comment]
Good call
