### ISSUE TITLE
Can't use v2.1.22 with Bower and Browserify

### ISSUE THREAD

**Issue by StanislauTarazevich** [bevacqua/rome#133]
When I try to build a bundle using Browserify and rome as bower package I get the following message:

`Error: Cannot find module './throttle' from 'path/to/bower_components/rome/dist'`

v2.1.21 works well.
As I understand it happened because `_dereq_` was replaced with `require`.

NPM version works well though because main file is `src/rome.moment.js` and there are all necessary files in `src` folder. But in bower version main file is `dist/rome.js` and there are no separate modules in `dist` folder so they can't be required.

**Comment by bevacqua** [comment]
Don't. Use `npm` and browserify
