### ISSUE TITLE
How to unbind click handler from rd-date.

### ISSUE THREAD

**Issue by tarach** [bevacqua/rome#134]
I want to use rome as sidebar calendar for articles in my laravel projects. 

Unfortunately I can't disable its datepicker functionality. Every time i click on a day my current day gets deselected. 

I have tried even:
```javascript
// (...)
this.disableClicks = function()
{
    ths.disableAllElementClicks($(ths.elem));
};
this.disableAllElementClicks = function(elem)
{
    elem.children().each(function()
    {
        $(this).off();
        $(this).unbind();
        this.click = null;
        ths.disableAllElementClicks($(this));
    });
};
// (...)
//.on('ready', C.disableClicks);
```
But it doesn't work. How can I access calendars crossvent object and remove 'pickDay' on rb-date click event?

**Comment by bevacqua** [comment]
Use `.destroy()` on the calendar
