### ISSUE TITLE
IE11

### ISSUE THREAD

**Issue by cpt-chewieeee** [bevacqua/rome#158]
I am testing rome calendar on IE11, but nothing is showing up. Does rome support IE11?

**Comment by cpt-chewieeee** [comment]
So I try the demo and it works for IE10. 

Here's my code:

Deadlines (require): <input class="deadline" id="deadline">
rome(deadline);

This works in chrome, but in IE11, i get 'deadline' is undefined

**Comment by bevacqua** [comment]
You should find DOM elements using `deadline = document.querySelector('.deadline')` instead of relying on window.deadline to exist based on the input's `id`.

**Comment by cpt-chewieeee** [comment]
thank you for your quick response :+1:
