### ISSUE TITLE
Including rome in a debug browserify break source maps

### ISSUE THREAD

**Issue by glan** [bevacqua/rome#33]
If rome is included in a browserify build which has debug: true option set the exported source maps fail to be read by the browser.

**Comment by giovannibonetti** [comment]
When I try to use the JS console in Chrome for debugging, if Rome is included I can't see my breakpoints or where in the code I am. It always gets stuck at this line from *rome.js*:

![screenshot 2015-11-07 12 08 05](https://cloud.githubusercontent.com/assets/3451581/11015500/572f8cf6-8548-11e5-80d9-95c14225e129.png)

I really like this library, but whenever I am debugging JS I have to turn it off temporarily.
