### ISSUE TITLE
Update options after init?

### ISSUE THREAD

**Issue by neonsilk** [bevacqua/rome#37]
I have two inline pickers to represent a range. I want to prevent the user from navigating to a month before the start date in the end date picker, and vise-versa (since all of the dates are excluded by the date validator, anyway). To implement this behavior, I'll need to update the min/max when the user picks a date in either picker. It doesn't seem like there's a way to update options after initialization without destroying the pickers first.

So, I tried destroying/restoring the pickers each time a user picks a date, but the `options.reset()/options({ })` methods don't seem to work with inline pickers. See http://jsfiddle.net/yaz9wsd5/

When I call reset, the picker disappears. Calling `.show()` after reset reveals the picker again, but the container element is no longer inside the associated element, and is instead appended to the document body. Is this behavior expected?

**Comment by bevacqua** [comment]
Fixed in `2.0.1` http://jsfiddle.net/yaz9wsd5/2/
