### ISSUE TITLE
Using Rome with React

### ISSUE THREAD

**Issue by cayuu** [bevacqua/rome#55]
Others using [React](https://facebook.github.io/react/) this may be helpful:

> **tl;dr** React component lifecycle will by default cumulatively add event listeners to any `rome` instances in the component. **So. much. Event.** 
> **Current fix thoughts:** Store rome rendered state (and only apply when "new"), OR monkey patch `contra.emitter` OR destroy and rebuild Rome every `componentWillUpdate` + `render` cycle.

Injecting a `rome` instance into a React component looks something like this:

``` js
var calComponent = React.createClass({
  render: function () {
    if (this.refs.rome) {
      rome( this.refs.rome.getDOMNode() ).on('data', function () { console.log('fire!'); });
    }
    return (
      <div>
        <div ref="rome"></div>
      </div>
    );
  }
});
```

Rome events are intended and expected to be added _once_ to your `rome` instance. In a normal DOM render cycle, this is the case.

Not in React. When your component updates (setting state for example) every React `render()` cycle re-adds the events to your now stored (via virtual DOM references) `rome` instance, and you end up with multiple unexpected listeners. (ie. you'll see `"fire!"` logged repeatedly to your console on changing dates).

This is **NOT** specifically an issue with Rome. It exhibits due to unexpected (from Rome's perspective) rendering lifecycle.

Initially handled this by monkey-patching `contra.emitter` with an `.only(type,fn)` listener that overwrites the `evt = {}` (so there is only ever _one_ listener on `type`, it never uses 'push()' to expand the array of listeners - ymmv). Now storing a render state value in the React component itself, only applying event watchers when the _component_ state has not yet been handed a `rome#` instance from `rome()`.

Another option is to destroy the `rome` instance on the React `componentWillUpdate` lifecycle method and rebuild a new one on re-render, but this will reset any user state on the `rome` instance (like the new date they selected etc).

:space_invader:

**Comment by BenjaminRCooper** [comment]
Is it possible for rome to be a stateless component?

**Comment by Juanelorganelo** [comment]
Just in case, this works
```js
class Rome extends React.Component {
  constructor(props) {
    super(props);
    
    this.onRomeData = this.onRomeData.bind(this);
  }
  
  componentDidMount() {
    const romeNode = ReactDOM.findDOMNode(this.romeRef);
    this.rome = rome(romeNode);
    this.rome.on('data', this.onRomeData);
  }
  
  componentWillUnmount() {
    this.rome.off();
  }
  
  onRomeData() {
    console.log('Fire!!');
  }
  
  render() {
    return <input type="text" ref={r => { this.romeRef = r }} />;
  }
}
```

see [this pen](https://codepen.io/Juanelorganelo/pen/WENVKK)

**Comment by fmsouza** [comment]
In today's ecosystem, this is how I got things to work
react: ^16.4.2
react-dom: ^16.4.2
@bevacqua/rome: ^3.0.3

```javascript
import React, { createRef, useEffect } from 'react';
import PropTypes from 'prop-types';
import moment from 'moment';
import rome from '@bevacqua/rome/src/rome';
import '@bevacqua/rome/dist/rome.min.css';

rome.use(moment);

export const DatePicker = props => {
  const { onSelectDate } = props;
  const elementRef = createRef(null);
  const pickerRef = createRef(null);
  useEffect(() => {
    pickerRef.current = rome(elementRef.current, { monthsInCalendar: 2 });
    pickerRef.current.on('data', data => onSelectDate(data));
    return () => pickerRef.current.off();
  }, []);

  return <div ref={elementRef} />;
};

DatePicker.propTypes = {
  onSelectDate: PropTypes.func.isRequired
};

```
