### ISSUE TITLE
Demos with predefined range do not work

### ISSUE THREAD

**Issue by kapooostin** [bevacqua/rome#57]
On demo page ```Pick a date between 2013-12-30 and 2014-10-01``` and the next one do not work properly. Arrows are not clickable so you cannot list the calendar to allowed range to set a date.

Time input also ignores clicks.

**Comment by dohzya** [comment]
Same here (on Chrome 39 - Yosemite)

**Comment by bevacqua** [comment]
Resolved in `1.2.3`. Sorry for the long wait.
