### ISSUE TITLE
Navigating through months is changing the actual selected date

### ISSUE THREAD

**Issue by suzana-zevri** [bevacqua/rome#59]
The original selected date is updated with a new one every time I change the month and the 'data' event is emitted. Is it possible to only browse through the months (with no event triggered) and set the new date only when clicking the actual days?

**Comment by bevacqua** [comment]
Currently, no. The thinking is that the user will eventually arrive at the date they want, and this way there's always _(barring the scenario an entirely invalid month)_ a selected date.

You're welcome to submit a pull request making the behavior optional.
