### ISSUE TITLE
Customizing

### ISSUE THREAD

**Issue by arjunmenon** [bevacqua/rome#6]
Hi
Want to add some additions.
1. Ability to show events/holidays on some days when mouse is hovered.
2. Addition of shortcuts to calendar, for eg "Today". Also adding list of coming months, so easy traversing diff months, like this is JULY, so add "AUG", "SEPT", "OCT", "NOV", "DEC".
3. Highlighting weekends.
4. Range Picker, so coordination b/w two inputs.

Thanks.

**Comment by katiasmet** [comment]
Anyone who wants to highlight weekends, you can do this with css :). 

```css
.rd-day-body:last-child,
.rd-day-body:nth-last-child(2) {
    /* Your CSS */
 }
```

**Comment by ROBERT-MCDOWELL** [comment]
create a PR please

**Comment by katiasmet** [comment]
This is just css that people can add :). It's not a the best solution for a PR ;). Ideal would be if t here was an extra class on weekends. 
At the moment I haven't got the time for this fix
