### ISSUE TITLE
Set default date based on first cal value

### ISSUE THREAD

**Issue by omarfouad** [bevacqua/rome#60]
I have two instances of rome bound together to validate a range between their two dates. Is it possible to have the second calendar to open on the same month of the first calendar's date by default?

For example if today is 2015-01-10, the first calendar open up showing today, but I set a date on next October. When I set the ending range on the second calendar, I have to navigate all the way to October to start choosing a valid `end date`. Can the second calendar show the October month instead?

**Comment by bevacqua** [comment]
There's a few ways you could do this.

You could listen for changes on both calendars and whenever one changes set the date on the other one.

You could also listen for either calendar being shown an adjust the date as they're displayed, according to the other  calendar.

**Comment by omarfouad** [comment]
Thanks for the reply, but that will actually show the date in the input field. I just want to change the default date that is seen when the calendar is displayed. Ideas?

**Comment by bevacqua** [comment]
Yup, you can use `.setValue(date)`

**Comment by omarfouad** [comment]
Yes, that's what I was looking for. Didn't work before because I had to wait for the `ready`event to dispatch. 

Have a great Sunday!

**Comment by bevacqua** [comment]
In 2.0.0 you won't have to wait for `'ready'` anymore :)

**Comment by omarfouad** [comment]
Yeah I just noticed ✌️
