### ISSUE TITLE
Positioning the calendar widget

### ISSUE THREAD

**Issue by omarfouad** [bevacqua/rome#62]
I'm trying to assign the `.container` property to a DOM element (actually above the input field), but with no luck. Ideas?

**Comment by omarfouad** [comment]
Or should I use that property as a read-only one?

**Comment by omarfouad** [comment]
What I'm trying to do is to have the calendar displayed *above* the input and not *below* it. One approach was to inline the calendar inside of a styled container, which worked (I could manage to bind the input and the calendar values).
 
However the scenario is, the user should click on an icon, the container pops up showing the calendar, when the user clicks on a new date the container gets out of the way and the input is updated:

```js
current.on('data', function() {
	scope.pickerDate = this.getDateString();
	scope.$apply();
        $(element).find('.datepicker-container').hide();
});
```
Unfortunately, listening to the `data` event isn't efficient enough as it is also dispatched when the user navigates the months of the calendar, resulting on a sudden close. 

![rome](https://cloud.githubusercontent.com/assets/693696/5698122/e10c4af6-9a05-11e4-85d6-067218ee08cc.gif)

This happens because the date changes when the month is switched thus the data event. Would be great if the selected date doesn't change while navigating the months, but just when the actual day is clicked on the calendar.

**Comment by bevacqua** [comment]
As to the positioning issue I would attempt to come up with a positioning API so that people are able to position the calendar however they please, if they don't want the default "below the input when clicking on it" behavior.

Not changing the selected date when navigating through months has been requested a few times. I would accept pull requests making that behavior optional.

As for the last issue, consider setting a hard height for the calendar, as a temporary fix

**Comment by omarfouad** [comment]
Cool. Let me see what I can do.

**Comment by danmo** [comment]
Hi, any update on this one ?

**Comment by omarfouad** [comment]
@danmo No news on this.

**Comment by dsully1992** [comment]
Hi @omarfouad, can you share your positioning code with me? I'm struggling to position my calendar above its associated input field. Slightly different from your scenario, my input field really only need be a text field (read only); I just made it a read only input field to avoid inline without adding a button.
