### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by ChristoforosKor** [bevacqua/rome#63]
hello, I am trying to use the calendat but I get this error
Uncaught TypeError: undefined is not a function
calendar.js:64 
initcalendar.js:48 
calendarinput.js:1 
inlinecore.js:24 core
κουπόνι-ημέρας.html:565 (anonymous function)

the code i use is
 <script src="media/com_elgbetstats/js/rome.js" type="text/javascript" ></script>
 <input id='ivp' class='input' />
 <script type="text/javascript">
       rome('ivp');
 </script>

In the same page are also loaded jquery and select2.

**Comment by ChristoforosKor** [comment]
I am sorry , the code I use is

`<script src="media/com_elgbetstats/js/rome.js" type="text/javascript" ></script>`
  `<input id='ivp' class='input' />`
  
  `<script type="text/javascript">`
      ` rome('ivp');`
    ` </script>``

**Comment by bevacqua** [comment]
You need to pass a DOM element, not a selector, or whatever `'ivp'` means.
