### ISSUE TITLE
Positioning of bound datepickers

### ISSUE THREAD

**Issue by Passenger-Inspired** [bevacqua/rome#70]
Is their a way to change the position of the absolutely positioned instance?

Maybe it is best to add a property such as 'reposition' which takes into account the viewport? Similar to what Pikaday does.

Ben

**Comment by bevacqua** [comment]
Not yet, but it's somewhere on the roadmap. See #62.

**Comment by ivobenedito** [comment]
+1 for a positioning API or a reposition based on the available viewport ... would be awesome :)!
