### ISSUE TITLE
Feature: Auto close only on day or time select

### ISSUE THREAD

**Issue by MitMaro** [bevacqua/rome#75]
I would like to have the calendar only hide when the time is selected but not the date. I know I can do this by disabling the autoClose and adding some event listeners outside of Rome.

I think, however, that it would make a nice addition to Rome to have autoClose take an optional value of 'time' or 'day' that would only close when the respective item is selected.

I would be happy to add a pull request with this option if it's a desired feature.

**Comment by bevacqua** [comment]
Sounds fine to me, you're welcome to create the pull request.
