### ISSUE TITLE
Pull Requests...require authorization?

### ISSUE THREAD

**Issue by olivermuc** [bevacqua/rome#79]
Heya!
I'm new to the GITHub world, so bear with me. Tried to create a pull req, but it throws an error regarding authentication/authorization?! I'm using the Mac GUI client. 
Any ideas?
Thx,
O.

**Comment by bevacqua** [comment]
See: https://help.github.com/articles/creating-a-pull-request/

**Comment by olivermuc** [comment]
Lol, I may be new to GIT, but I know well enough not to ask before having read the manual.
Like I said, I'm getting auth errors, and the docs suggest you need to add me to the authorized contributors.

**Comment by bevacqua** [comment]
I don't have experience with the Mac GUI, try creating the pull request using the web interface

**Comment by olivermuc** [comment]
I haven't tried forking first (to own a copy and create a branch), I was hoping that wasn't necessary. But it appears as the only option available to me. With your repo I can't seem to first create a branch, against which I can then do a pull req.

**Comment by bevacqua** [comment]
You need to fork, otherwise you'd be pushing directly into my repository, and you don't have access for that.
