### ISSUE TITLE
not working on ie8, ie11, opera 12.16 when picker is inside <form> tag

### ISSUE THREAD

**Issue by f1194841** [bevacqua/rome#83]
not working on: ie11, ie8, opera 12.16 when date picker is inside ```<form>``` tag

**Comment by bevacqua** [comment]
What is it that is not working?

**Comment by f1194841** [comment]
for example:

that work on ie11, ie8 and opera 12.16:

```
<div class='parent'>
    <label for='dt'>Pick a date and a time: </label>
    <input id='dt' class='input'>
</div>
```

thats not work on ie11, ie8 and opera 12.16 but works on chrome and firefox:

```
<form>
<div class='parent'>
    <label for='dt'>Pick a date and a time: </label>
    <input id='dt' class='input'>
</div>
</form>
```

**Comment by alexkavon** [comment]
I receive an error in the Console Log on IE 11 that says:

~~~
begin is not defined
~~~

Here is my code. It looks like IE doesn't like the variable approach to selecting the calendar via id. Thoughts?

~~~
rome(begin, {
        time: false,
        inputFormat: "MMM DD, YYYY",
        initialValue: $scope.edit.date.begin
      }).on('data', function(value) {
        $scope.edit.date.begin = value;
      });
~~~

**Comment by bevacqua** [comment]
- This is a separate issue
- You shouldn't rely on the `window.id` pattern in real applications. That was just demo code. Use `getElementById`
