### ISSUE TITLE
Typed dates don't work from 2.1.10+

### ISSUE THREAD

**Issue by steveneaston** [bevacqua/rome#87]
Typing a date worked in version 2.1.9 and below ([example with 2.1.9](https://jsfiddle.net/n9ur2ss4/1/)) but after the `Date.now()` → `new Date()` change in 2.1.10 you can no longer type a date ([example with 2.1.10](https://jsfiddle.net/n9ur2ss4/) and version [2.1.13](https://jsfiddle.net/n9ur2ss4/3/)).

**Comment by bevacqua** [comment]
Many thanks. This is fixed in `2.1.14`
