### ISSUE TITLE
How do we change the locale/set locale dates?

### ISSUE THREAD

**Issue by Fatemama** [bevacqua/rome#89]
Hi,

I don't see any reference to moment localization?
I'd like to present french translation of days and months using locale, is this feature under developpment or would be released in future version?

Thanks,
F

**Comment by bevacqua** [comment]
Change it on `moment` directly, using their API

**Comment by Aiderlei** [comment]
Can someone provide an example within the readme?

**Comment by Aiderlei** [comment]
I posted [an example](https://github.com/bevacqua/rome/issues/218#issuecomment-1895606715) on how to localize rome with moment.
