### ISSUE TITLE
Calendar is very small when using Bootstrap

### ISSUE THREAD

**Issue by bvp** [bevacqua/rome#93]
Calendar is very small when using Bootstrap
Without using Bootstrap
![without_bootstrap](https://cloud.githubusercontent.com/assets/284156/6866306/f00b5972-d487-11e4-9198-ffa16d39600f.png)

With Bootstrap
![with_bootstrap](https://cloud.githubusercontent.com/assets/284156/6866308/f5d79e42-d487-11e4-82a7-2be62a8af1c7.png)

Possible conflict styles

**Comment by bevacqua** [comment]
So style it, that's the whole point.

**Comment by bvp** [comment]
can you show me example? =)

**Comment by bevacqua** [comment]
```css
.rd-day-body {
  padding: 10px;
}
```
