### ISSUE TITLE
IE error: Unable to get property 'removeChild' of undefined or null reference

### ISSUE THREAD

**Issue by StanislauTarazevich** [bevacqua/rome#96]
There's an issue in IE (10 and 11, did not check previous versions). After any date picker container is removed from DOM every other 'destroy' call on any other date picker causes the following error:
```
Unable to get property 'removeChild' of undefined or null reference
```
The following pull request fixes the issue: https://github.com/bevacqua/rome/pull/95

**Comment by bevacqua** [comment]
Thank you. Should make it in the next patch :)

**Comment by bevacqua** [comment]
This is fixed in `2.1.17`

**Comment by Rambou** [comment]
@bevacqua What was the fix for this? the commit is not linked with this issue.

**Comment by harshamehra** [comment]
@bevacqua Hi , what is the fix of this issue ? I have been dealing with this in IE v11 working on ext-js .

**Comment by GBT3101** [comment]
This issue is back
